### ISSUE TITLE
Create Branches / TAGS between 2 snapshots 

### ISSUE THREAD

**Issue by fanaticjo** [apache/iceberg#9280] opened 2023-12-12 03:30 UTC
### Feature Request / Improvement

Is there a way where we can create a branch / TAG based on 2 snapshot ids or only latest data 

We have a use case where we write monthly generated report to a iceberg table , but for every month we want to tag / branch the data for audit purposes . 

Currently branch / tag creates the data from that snapshot to first snapshots . 

### Query engine

Spark

**Comment by nastra** [comment] 2023-12-12 08:32
closing as this is a duplicate of https://github.com/apache/iceberg/issues/9281

**Closed by nastra** 2023-12-12 08:32 UTC
