### ISSUE TITLE
Concurrent writes from multiple Spark drivers to S3 support

### ISSUE THREAD

**Issue by borislitvak** [apache/iceberg#1912] opened 2020-12-11 08:37 UTC
Can we perform concurrent writes from multiple Spark drivers to S3 with Iceberg without data loss/corruption?

Background: 

- Delta.io [s3 documentation states](https://docs.delta.io/latest/delta-storage.html) that
"Concurrent writes to the same Delta table from multiple Spark drivers can lead to data loss."
- With AWS announcement on [S3 consistency](https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/), does this relax the requirements in any way?

Thanks, Boris

**Comment by aokolnychyi** [comment] 2020-12-11 10:34
Iceberg avoiding listing and renames by design and does not have this limitation as long as you use Iceberg [Hive catalog](http://iceberg.apache.org/java-api-quickstart/#using-a-hive-catalog).

**Comment by borislitvak** [comment] 2020-12-11 12:09
For future visitors looking to compare s3 ACID data lake solutions, this scenario over S3 is not supported in Hudi/Delta and there does not seem to be a path for such a support. 
So Iceberg is a clear winner in this regard!

Sources:
[Delta.io](https://github.com/delta-io/delta/issues/564)
[Hudi](https://github.com/apache/hudi/issues/2330)

How did you accomplish this, @aokolnychyi ?

**Comment by vinothchandar** [comment] 2020-12-11 15:42
FWIW the answers I gave are for Hudi are for the case that does not need an external server like Hive. So its not quite apples-apples.

**Comment by HeartSaVioR** [comment] 2021-01-11 00:40
@borislitvak 
I'd suggest closing the issue, as the answer is already provided and no further discussion is expected.

**Closed** 2021-01-11 06:08 UTC
