### ISSUE TITLE
Ignore downcasting of column types when "mergeSchema" is set.

### ISSUE THREAD

**Issue by schatterjee10** [apache/iceberg#4849] opened 2022-05-24 01:49 UTC
We encountered an error while writing to iceberg table
`java.lang.IllegalArgumentException: Cannot change column type: myCol: long->int`
The table was created with long type for myCol. We are writing to Iceberg table from Spark application like this :
`df.writeTo(icebergTable).option("mergeSchema", "true").overwritePartitions()`
 
Since we have datatype for myCol as int in the dataframe and we are using 'mergeSchema' option, I believe the writer is trying to downcast the column type which is failing. Would it be better if we ignore the downcasting of column types with 'mergeSchema' option?

**Comment by kbendick** [comment] 2022-05-26 06:13
Thanks for reporting this @schatterjee10.

I’d be open to a quick demo PR, but I do worry about trying to be very “smart” with casting rules. We do allow for “incompatible” schema updates to be made, but this would require casting the data afaik and `mergeSchema` should really err on the side of caution in my opinion.

That said, if you have a sample draft POC to show this is possible, I think we’d be willing to take a look to consider it. Again though, to be really correct the data should be stored in the files as long (in my opinion) and should likely be casted.

But I will admit I’m not super familiar with this code so if it can be easily resolved, feel free to present it or discuss it. But in general, I’m hesitant about overriding the built in rules about dangerous casting. Eventually, I worry it will come back to bite us.

I’m just one person so others might disagree, but that’s my 2 cents fwiw.

**Comment by kbendick** [comment] 2022-05-26 06:21
For what it’s worth, here’s the original PR that added support.

There’s a function in `SchemaUtils` it seems you can look into to check viability / ease of adding this change: https://github.com/apache/iceberg/commit/69c06cead6e5ddfe58c17630c4863eb98e04ff4e

**Comment by kbendick** [comment] 2022-06-05 03:46
But TLDR is that downcasting from long -> int is not safe.

It could break existing data in the table.

If you’re _sure_ that the change is allowed, I’d suggest you use the Java API to allow for incompatible changes.

Even with `overwritePartitions()`, there could be data in _other_partitions that has true long types that don’t fit into int.

I’m going to close this issue as this is the expected behavior and downcasting in an unsafe way is not something `mergeSchema` should do on the users behalf.

You can use the Java API to allow for incompatible schema changes (at your own risk as long -> int is a lossy conversion for values greater than INT_MAX). Feel free to open a new issue if you still have issues 🙂

**Comment by RussellSpitzer** [comment] 2022-06-05 19:15
@kbendick I do think we should allow this, just ignoring the schema change. Currently the behavior of merge schema invalidates a write that would succeed if mergeSchema had been set to false.

I think in cases like this merge schema should just not downcast and allow the write to proceed as normal. This would be really useful for users who have multiple numeric sources and want to use mergeSchema functionality. Mostly the merge schema is being used for adding new missing columns but if an existing column has a wider type (or was widened by another operation) I don't think that should break anything

**Comment by kbendick** [comment] 2022-06-05 19:17
Ok. I’m good with that argument.

Specifically that this write would succeed otherwise. I do worry about unintended consequences from eventually aggressively checking widening, but int and long are good in my book.

Thanks for weighing in @RussellSpitzer

**Comment by kbendick** [comment] 2022-06-05 19:27
If anybody is interested in working on this, as I mentioned before the best place to start the work would be around here as this method is where the `mergeSchema` logic begins: https://github.com/apache/iceberg/commit/69c06cead6e5ddfe58c17630c4863eb98e04ff4e#diff-9eb9256d82cd6ab19f73c941a7011ff4973eb61255c7fee0b38402f922a2e48cR239

**Comment by yyy1000** [comment] 2023-12-06 05:51
Since no one is working on this, I'd like a try.

**Comment by sfc-gh-jleang** [comment] 2024-07-19 22:48
I'll take a stab at this one.

**Comment by leangjonathan** [comment] 2024-07-19 22:51
I'd like to try this one

**Comment by RussellSpitzer** [comment] 2024-07-20 02:47
We generally do not assign Issues, please post a PR or respond here if you have any questions and we'll be glad to help out :)

**Comment by rocco408** [comment] 2024-10-29 06:23
I might have a fix in https://github.com/apache/iceberg/pull/11419. This is my first PR here, I'm open to any thoughts if folks have a minute. Cheers.

**Closed** 2024-11-15 06:07 UTC
Labels: good first issue
