### ISSUE TITLE
Types + Filesystem - custom implementations VS Arrow

### ISSUE THREAD

**Issue by CircArgs** [apache/iceberg#3464] opened 2021-11-03 23:16 UTC
I've been looking through the python legacy code as well as the new pythonic version and I had a few questions about the python rewrite and the lack of use of existing projects in the ecosystem. 

# Types
 in https://github.com/apache/iceberg/blob/master/python/src/iceberg/types.py there are a few primitive types whose comparison requires using the instantiated attributes rather than python built-ins. It also seems this is still being modeled after the Legacy version insofar as using separate types for "types" and "literals" https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/types/types.py. It seems to me it would be more natural to have a singular class for each primitive to act as a type and literal maybe something loosely like https://gist.github.com/CircArgs/a4571332d72888e3773f66bd180bb0e0

# Arrow?
From the types I was also looking around legacy at the filesystem and such and overall was curious why everything was going the way of custom when pyarrow openly implements a filesystem API https://arrow.apache.org/docs/python/filesystems.html for s3, hdfs and local and consistent types https://arrow.apache.org/docs/python/api/datatypes.html which has aptly named equivalent types for each of those described in the iceberg spec https://iceberg.apache.org/#spec/#primitive-types.

Is there some opposition to building off of Arrow which is of course another Apache project that's well maintained and used by projects also likely to benefit from iceberg such as Dask?

**Comment by TGooch44** [comment] 2021-11-04 01:04
short answer is that legacy was mostly implemented before pyarrow was v1 and before any datasets API was available.  At Netflix, These things were being delegated to an internal c-lib based off the arrow c-lib that handled low-level scanning and filtering. 

Additionally, AFAIK, even in the current pyarrow datasets api there is still some special handling where schema evolution is needed that somewhat prevents using the full capability there. Last I checked you have to have a single schema across files scanned in the Dataset, which may not be the case in Iceberg.  

However, strong agree that any new implementation should leverage arrow as much as possible and should strive to work with arrow community to shore up any functionality gaps(where it makes sense for their project to do so).

**Comment by jun-he** [comment] 2021-11-04 02:19
Thanks for the comments on the Types. There are two primitive types not fitting this, e.g. `FixedType`, which depends on instantiating attribute `length`, e.g. `FixedType(16)` and `FixedType(8)` are two different types, (similar to int32 vs int64). I don't see a clean way to provide a singular class for both two.

**Comment by CircArgs** [comment] 2021-11-04 19:59
@jun-he could you elaborate a little more? It seems these fixed types are just for raw bytes. What prevents a singular type like one having a `length` attribute?

**Comment by jun-he** [comment] 2021-11-05 06:26
Sure, following your snippet to define fixed type as follows
```
@handle_null
@dataclass(order=True)
class Fixed(Type):
    value: bytes
    length: int
...

fixed = Fixed(string.encode(encoding), 8)
```
which is type with data as well.

But we also need a way to indicate `Fixed(8)` type/class without data for many cases. 
I am curious if there is a clean way to provide a singular class for this.

**Comment by CircArgs** [comment] 2021-11-06 01:48
@jun-he thanks a lot for the explanation. I have a good idea of what you're describing I think. I definitely dont want to seem like I'm making an argument for types to be based on dataclasses or anything I just used them to get the more auto implemented methods for free for my example (and I still had to make the decorator to account for the special null behavior I saw in the legacy python implementation). 

It still seems to me that the fixed types fit well into a the model I tried to describe though. What do you think about something like (also in the updated gist https://gist.github.com/CircArgs/a4571332d72888e3773f66bd180bb0e0):

```python
@dataclass
class _FixedTypeBase(Type):
    '''base fixed type for behavior of a fixed type e.g. FixedType[16]'''
    value: bytes
        
    def __repr__(self):
        return f'FixedType{self._length}(value={self.value})'
    
    def __str__(self):
        return repr(self)

class FixedTypes:
    implemented: Dict[int, _FixedTypeBase]=dict()
    
    def __getitem__(self, length: int):
        if length in self.implemented:
            return self.implemented[length]
        else:
            class _FixedType(_FixedTypeBase):
                _length = length
            self.implemented[length]=_FixedType
            return _FixedType
        
    

FixedType=FixedTypes()

#usage
# FixedType[16](string.encode(...))
FixedType[16]==FixedType[16]
```

I went with this pattern in case there's a need for types of arbitrary length, but if they were to be just 8, 16, 32, 64, ... then I could see why they might just be written out fully without this.

**Comment by samredai** [comment] 2021-11-06 03:02
One thing I noticed about how types.py is currently is that because the types are a mix of classes (`DecimalType`, `FixedType`, etc) and instances (`BooleanType`, `IntegerType`, etc), checking a type is a little inconsistent. For example:
```py
type_1 = FixedType(8)
isinstance(type_1, FixedType)  # True

type_2 = BooleanType
isinstance(type_2, BooleanType)  # False
type_2 == BooleanType  # True
```

If using dataclasses gives us the expected behavior for all relevant dunder methods (or even 90%, we can override any of them), and it allows us to consolidate the logic in literals.py and types.py, that would cut down the code significantly. I think it's worth trying out and validating against existing tests.

**Comment by rdblue** [comment] 2021-11-07 22:11
@samredai, I agree. If we can fix the problem that some types are actually instances, that would be great. I'm not sure how to do that though.

**Comment by samredai** [comment] 2021-11-08 20:59
@CircArgs there is a python sync on Wednesday this week where we will touch on the question of when and where to use pyarrow. As for combing types and literals into single classes with the class itself being passed around as the type, if you can validate that idea against the [existing tests](https://github.com/apache/iceberg/tree/master/python_legacy/tests/api/expressions) for literals and types, it would be a step in a positive direction imo.

**Comment by jun-he** [comment] 2021-11-10 07:11
@CircArgs This is an interesting idea. IIUC, we actually buffer the FixedType and will 
```FixedType[16](string.encode("foo")) and FixedType[16](string.encode("bar")) ``` write to the same object's `value: bytes` field?

@samredai yep, `isinstance(type_2, BooleanType)  # False` is false as BooleanType is actually an instance and ``isinstance(type_2, Type) ` will be true. 

In the transforms PR(https://github.com/apache/iceberg/pull/3450), I have to deal with them separately, which is less ideal. Hope we can find a viable path to unify them.

**Comment by emkornfield** [comment] 2021-11-10 21:00
> However, strong agree that any new implementation should leverage arrow as much as possible and should strive to work with arrow community to shore up any functionality gaps(where it makes sense for their project to do so).

Regarding Arrow, has there been any thought of developing lower level components for iceberg in C++ and have python bindings to them? I'm not sure what the best mode for collaboration but one example of cross project collaboration is the parquet C++ library is still technically under the Parquet PMC governance, but lives in the Arrow repo. At some point Arrow would like to have a C++ implementation for iceberg (at least I would like to see one).

**Comment by rdblue** [comment] 2021-11-11 01:06
I'd love to see a C++ implementation of Iceberg! But I'm not sure that it is needed for a good python experience. That seems to me like a longer route. Iceberg is a fairly simple format, with most of the complexity in the actual columnar formats. Job planning doesn't usually take that long compared to actually running queries.

**Comment by Fokko** [comment] 2023-10-02 09:05
I'm closing this one since we're migrating to the iceberg-python repository. I see some great discussion here. We're already moving stuff to C++, and Arrow is currently still an optional dependency, so I think we made the right decision to implement the types ourselves. Also, the types in Python are just a tiny wrapper around the C++ object and a lot of stuff is not available in the Python API.

**Closed** 2023-10-02 09:12 UTC
Labels: python
