### ISSUE TITLE
PyIceberg AWS credential error

### ISSUE THREAD

**Issue by marty-sullivan** [apache/iceberg#7566] opened 2023-05-09 04:49 UTC
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

I'm trying out PyIceberg v0.3.0 installed via conda-forge 

I'm trying out some queries to an AWS Glue schema. The following runs fine and returns the expected catalog items from glue:

```python
from pyiceberg.catalog import load_catalog

catalog = load_catalog("glue")
print(catalog.list_tables('my_database'))
```

However when I run:

```python
channels = catalog.load_table('my_database.iceberg_test')
```

I get the following error:

```
Traceback (most recent call last):
  File "/mnt/persistent/composite-generators/test/iceberg/intro.py", line 8, in <module>
    channels = catalog.load_table('my_database.iceberg_test')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/pyiceberg/catalog/glue.py", line 278, in load_table
    return self._convert_glue_to_iceberg(load_table_response.get(PROP_GLUE_TABLE, {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/pyiceberg/catalog/glue.py", line 179, in _convert_glue_to_iceberg
    file = io.new_input(metadata_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/pyiceberg/io/fsspec.py", line 243, in new_input
    fs = self.get_fs(uri.scheme)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/pyiceberg/io/fsspec.py", line 280, in _get_fs
    return self._scheme_to_fs[scheme](self.properties)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/pyiceberg/io/fsspec.py", line 104, in _s3
    fs = S3FileSystem(client_kwargs=client_kwargs, config_kwargs=config_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/s3fs/core.py", line 187, in __init__
    self.s3 = self.connect()
              ^^^^^^^^^^^^^^
  File "/home/ec2-user/micromamba/lib/python3.11/site-packages/s3fs/core.py", line 292, in connect
    self.s3 = self.session.create_client('s3', aws_access_key_id=self.key, aws_secret_access_key=self.secret, aws_session_token=self.token, config=conf, use_ssl=ssl,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: botocore.session.Session.create_client() got multiple values for keyword argument 'aws_access_key_id'
```
It seems odd that I would get a credential error here, given that the previously mentioned code successfully queries my glue data catalog successfully.

At first, I thought it was an issue with my AWS profile, since it is using the newer `aws configure sso` profile through AWS Identity Center which isn't always supported by everything out there yet.

However, I tried explicitly setting `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` explicitly in my environment but I get the same exact error.

I'm not sure what my problem is, but it's confusing that my AWS credential profiles & environment variables would work for some calls but not others. I will also be very clear, I have no AWS credential problems with any other item at the moment, just this test I was doing with PyIceberg.

**Comment by Fokko** [comment] 2023-05-09 06:57
Thanks for raising this @marty-sullivan. Could you maybe share the output of `pip freeze` to help me debug this issue?

**Comment by marty-sullivan** [comment] 2023-05-09 14:27
No problem, here you go:

```
affine @ file:///home/conda/feedstock_root/build_artifacts/affine_1674245120525/work
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
asciitree==0.3.3
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work
aws-sam-translator @ file:///home/conda/feedstock_root/build_artifacts/aws-sam-translator_1682631387981/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1678797995786/work
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1682557255168/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1682551095207/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1666764686339/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2022.12.7
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179355965/work
cfn-lint @ file:///home/conda/feedstock_root/build_artifacts/cfn-lint_1682388296185/work
cftime @ file:///home/conda/feedstock_root/build_artifacts/cftime_1666833839601/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1678108872112/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1666798198223/work
click-plugins==1.1.1
cligj @ file:///home/conda/feedstock_root/build_artifacts/cligj_1633637764473/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
commonmark==0.9.1
configobj @ file:///home/conda/feedstock_root/build_artifacts/configobj_1674244895923/work
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1673633658026/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1681508576793/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1666829667355/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1682704095490/work
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1682707239884/work
docutils @ file:///home/conda/feedstock_root/build_artifacts/docutils_1666754865005/work
donfig @ file:///home/conda/feedstock_root/build_artifacts/donfig_1644081226051/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
fasteners @ file:///home/conda/feedstock_root/build_artifacts/fasteners_1643971550063/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1680980497582/work
future @ file:///home/conda/feedstock_root/build_artifacts/future_1673596611778/work
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808665953/work
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1675704792373/work
hive-thrift-py==0.0.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1682176699712/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1655568249366/work
jschema-to-python @ file:///home/conda/feedstock_root/build_artifacts/jschema-to-python_1637091457220/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpickle @ file:///home/conda/feedstock_root/build_artifacts/jsonpickle_1652300595122/work
jsonpointer==2.0
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
junit-xml @ file:///home/conda/feedstock_root/build_artifacts/junit-xml_1601482646955/work/junit_xml-1.9-py2.py3-none-any.whl
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1675806669059/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1674135794919/work
mmh3 @ file:///home/conda/feedstock_root/build_artifacts/mmh3_1667042145495/work
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1678312711771/work
netCDF4 @ file:///home/conda/feedstock_root/build_artifacts/netcdf4_1678981211535/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1667391556261/work
numcodecs @ file:///home/conda/feedstock_root/build_artifacts/numcodecs_1671214260840/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1682210216651/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1682331485183/work
parquet-cli==1.3
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1681246756246/work
pbr @ file:///home/conda/feedstock_root/build_artifacts/pbr_1673485161019/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1680694260721/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1678652433955/work
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1681775010077/work
pyarrow==12.0.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic @ file:///home/conda/feedstock_root/build_artifacts/pydantic_1679565264119/work
pygit2 @ file:///home/conda/feedstock_root/build_artifacts/pygit2_1680728313754/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pyiceberg @ file:///home/conda/feedstock_root/build_artifacts/pyiceberg_1675966948690/work
pykdtree @ file:///home/conda/feedstock_root/build_artifacts/pykdtree_1679338228358/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1680037383858/work
pyorbital @ file:///home/conda/feedstock_root/build_artifacts/pyorbital_1657594369239/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyproj @ file:///home/conda/feedstock_root/build_artifacts/pyproj_1680061975081/work
pyresample @ file:///home/conda/feedstock_root/build_artifacts/pyresample_1675782872428/work
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1672681471126/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
pyspectral @ file:///home/conda/feedstock_root/build_artifacts/pyspectral_1669149604943/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-geotiepoints @ file:///home/conda/feedstock_root/build_artifacts/python-geotiepoints_1679067933297/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1666772382226/work
rasterio @ file:///home/conda/feedstock_root/build_artifacts/rasterio_1683265313330/work
regex @ file:///home/conda/feedstock_root/build_artifacts/regex_1679599159927/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1682535435083/work
rich @ file:///home/conda/feedstock_root/build_artifacts/rich_1664752510089/work
s3fs==0.4.2
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1654039987929/work
sarif-om @ file:///home/conda/feedstock_root/build_artifacts/sarif-om_1637091281947/work
satpy @ file:///home/conda/feedstock_root/build_artifacts/satpy_1683034862414/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1683345249614/work/dist/scipy-1.10.1-cp311-cp311-linux_x86_64.whl#sha256=fdd8b060d44b81f57fcfbe5c0e73574a2cd2de7d47af0b0525b4b4831df85c48
shapely @ file:///home/conda/feedstock_root/build_artifacts/shapely_1679081555742/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
snuggs==1.4.7
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1679342590084/work
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
thrift @ file:///home/conda/feedstock_root/build_artifacts/thrift_1677754198327/work/lib/py
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1681817468880/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
trollimage @ file:///home/conda/feedstock_root/build_artifacts/trollimage_1675448725405/work
trollsift @ file:///home/conda/feedstock_root/build_artifacts/trollsift_1669046492835/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1665144421445/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1678635778344/work
xarray @ file:///home/conda/feedstock_root/build_artifacts/xarray_1682081841683/work
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1676835466992/work
zarr @ file:///home/conda/feedstock_root/build_artifacts/zarr_1678980110903/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1681770155528/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work
zstandard @ file:///home/conda/feedstock_root/build_artifacts/zstandard_1666867966255/work
```

**Comment by marty-sullivan** [comment] 2023-05-09 14:34
I realized the above `pip freeze` output is not great since the version information is missing due to conda/mamba internal things. Here is the conda/mamba compatible environment.yaml:

```yaml
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- affine=2.4.0=pyhd8ed1ab_0
- appdirs=1.4.4=pyh9f0ad1d_0
- arrow-cpp=12.0.0=ha770c72_1_cpu
- asciitree=0.3.3=py_2
- attrs=22.2.0=pyh71513ae_0
- aws-c-auth=0.6.26=h2c7c9e7_6
- aws-c-cal=0.5.26=h71eb795_0
- aws-c-common=0.8.17=hd590300_0
- aws-c-compression=0.2.16=h4f47f36_6
- aws-c-event-stream=0.2.20=h69ce273_6
- aws-c-http=0.7.7=h7b8353a_3
- aws-c-io=0.13.21=hcccde9c_3
- aws-c-mqtt=0.8.6=h3a1964a_15
- aws-c-s3=0.2.8=h0933b68_4
- aws-c-sdkutils=0.1.9=h4f47f36_1
- aws-checksums=0.1.14=h4f47f36_6
- aws-crt-cpp=0.19.9=h85076f6_5
- aws-sam-translator=1.66.0=pyhd8ed1ab_0
- aws-sdk-cpp=1.10.57=hf40e4db_10
- blosc=1.21.3=hafa529b_0
- bokeh=3.1.0=pyhd8ed1ab_0
- boost-cpp=1.78.0=h6582d0a_3
- boto3=1.26.121=pyhd8ed1ab_0
- botocore=1.29.121=pyhd8ed1ab_0
- brotlipy=0.7.0=py311hd4cff14_1005
- bzip2=1.0.8=h7f98852_4
- c-ares=1.18.1=h7f98852_0
- ca-certificates=2022.12.7=ha878542_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cairo=1.16.0=h35add3b_1015
- certifi=2022.12.7=pyhd8ed1ab_0
- cffi=1.15.1=py311h409f033_3
- cfitsio=4.2.0=hd9d235c_0
- cfn-lint=0.77.3=pyhd8ed1ab_0
- cftime=1.6.2=py311h4c7f6c3_1
- charset-normalizer=3.1.0=pyhd8ed1ab_0
- click=8.1.3=unix_pyhd8ed1ab_2
- click-plugins=1.1.1=py_0
- cligj=0.7.2=pyhd8ed1ab_1
- cloudpickle=2.2.1=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_0
- commonmark=0.9.1=py_0
- configobj=5.0.8=pyhd8ed1ab_0
- contourpy=1.0.7=py311ha3edf6b_0
- cryptography=40.0.2=py311h9b4c7bb_0
- curl=8.0.1=h588be90_0
- cytoolz=0.12.0=py311hd4cff14_1
- dask=2023.4.1=pyhd8ed1ab_0
- dask-core=2023.4.1=pyhd8ed1ab_0
- dataclasses=0.8=pyhc8e2a94_3
- distributed=2023.4.1=pyhd8ed1ab_0
- docutils=0.19=py311h38be061_1
- donfig=0.7.0=pyhd8ed1ab_1
- entrypoints=0.4=pyhd8ed1ab_0
- expat=2.5.0=hcb278e6_1
- fasteners=0.17.3=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.14.2=h14ed4e7_0
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- freetype=2.12.1=hca18f0e_1
- freexl=1.0.6=h166bdaf_1
- fsspec=2023.4.0=pyh1a96a4e_0
- future=0.18.3=pyhd8ed1ab_0
- geos=3.11.2=hcb278e6_0
- geotiff=1.7.1=h480ec47_8
- gettext=0.21.1=h27087fc_0
- gflags=2.2.2=he1b5a44_1004
- giflib=5.2.1=h0b41bf4_3
- glog=0.6.0=h6f12383_0
- gmp=6.2.1=h58526e2_0
- gmpy2=2.1.2=py311h6a5fa03_1
- h5py=3.8.0=nompi_py311h518a8e0_101
- hdf4=4.2.15=h501b40f_6
- hdf5=1.14.0=nompi_hb72d44e_103
- hive-thrift-py=0.0.1=py_1
- icu=72.1=hcb278e6_0
- idna=3.4=pyhd8ed1ab_0
- importlib-metadata=6.6.0=pyha770c72_0
- importlib_metadata=6.6.0=hd8ed1ab_0
- importlib_resources=5.12.0=pyhd8ed1ab_0
- jinja2=3.1.2=pyhd8ed1ab_1
- jmespath=1.0.1=pyhd8ed1ab_0
- jq=1.6=h36c2ea0_1000
- jschema-to-python=1.2.3=pyhd8ed1ab_0
- json-c=0.16=hc379101_0
- jsonpatch=1.32=pyhd8ed1ab_0
- jsonpickle=2.2.0=pyhd8ed1ab_0
- jsonpointer=2.0=py_0
- jsonschema=4.17.3=pyhd8ed1ab_0
- junit-xml=1.9=pyh9f0ad1d_0
- kealib=1.5.0=he7a6254_1
- keyutils=1.6.1=h166bdaf_0
- krb5=1.20.1=h81ceb04_0
- lcms2=2.15=haa2dc70_1
- ld_impl_linux-64=2.40=h41732ed_0
- lerc=4.0.0=h27087fc_0
- libabseil=20230125.0=cxx17_hcb278e6_1
- libaec=1.0.6=hcb278e6_1
- libarrow=12.0.0=h1cdf7b0_1_cpu
- libblas=3.9.0=16_linux64_openblas
- libbrotlicommon=1.0.9=h166bdaf_8
- libbrotlidec=1.0.9=h166bdaf_8
- libbrotlienc=1.0.9=h166bdaf_8
- libcblas=3.9.0=16_linux64_openblas
- libcrc32c=1.1.2=h9c3ff4c_0
- libcurl=8.0.1=h588be90_0
- libdeflate=1.18=h0b41bf4_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=h516909a_1
- libevent=2.1.12=h3358134_0
- libexpat=2.5.0=hcb278e6_1
- libffi=3.4.2=h7f98852_5
- libgcc-ng=12.2.0=h65d4601_19
- libgdal=3.6.4=h7239d12_1
- libgfortran-ng=12.2.0=h69a702a_19
- libgfortran5=12.2.0=h337968e_19
- libgit2=1.6.4=h747ad27_0
- libglib=2.76.2=hebfc3b9_0
- libgomp=12.2.0=h65d4601_19
- libgoogle-cloud=2.10.0=hac9eb74_0
- libgrpc=1.54.1=hcf146ea_0
- libiconv=1.17=h166bdaf_0
- libjpeg-turbo=2.1.5.1=h0b41bf4_0
- libkml=1.3.0=h37653c0_1015
- liblapack=3.9.0=16_linux64_openblas
- libnetcdf=4.9.2=nompi_hdf9a29f_104
- libnghttp2=1.52.0=h61bc06f_0
- libnsl=2.0.0=h7f98852_0
- libnuma=2.0.16=h0b41bf4_1
- libopenblas=0.3.21=pthreads_h78a6416_3
- libpng=1.6.39=h753d276_0
- libpq=15.2=hb675445_0
- libprotobuf=3.21.12=h3eb15da_0
- librttopo=1.1.0=h0d5128d_13
- libspatialite=5.0.1=h7d1ca68_25
- libsqlite=3.40.0=h753d276_1
- libssh2=1.10.0=hf14f497_3
- libstdcxx-ng=12.2.0=h46fd767_19
- libthrift=0.18.1=h8fd135c_1
- libtiff=4.5.0=ha587672_6
- libutf8proc=2.8.0=h166bdaf_0
- libuuid=2.38.1=h0b41bf4_0
- libwebp-base=1.3.0=h0b41bf4_0
- libxcb=1.13=h7f98852_1004
- libxml2=2.10.4=hfdac1af_0
- libzip=1.9.2=hc929e4a_1
- libzlib=1.2.13=h166bdaf_4
- locket=1.0.0=pyhd8ed1ab_0
- lz4=4.3.2=py311h9f220a4_0
- lz4-c=1.9.4=hcb278e6_0
- markupsafe=2.1.2=py311h2582759_0
- mmh3=3.0.0=py311ha362b79_3
- mpc=1.3.1=hfe3b2da_0
- mpfr=4.2.0=hb012696_0
- mpmath=1.3.0=pyhd8ed1ab_0
- msgpack-python=1.0.5=py311ha3edf6b_0
- ncurses=6.3=h27087fc_1
- netcdf4=1.6.3=nompi_py311h1717473_102
- networkx=2.8.8=pyhd8ed1ab_0
- nspr=4.35=h27087fc_0
- nss=3.89=he45b914_0
- numcodecs=0.11.0=py311hcafe171_1
- numpy=1.24.3=py311h64a7726_0
- oniguruma=6.9.8=h166bdaf_0
- openjpeg=2.5.0=hfec8fc6_2
- openssl=3.1.0=hd590300_2
- orc=1.8.3=hfdbbad2_0
- packaging=23.1=pyhd8ed1ab_0
- pandas=2.0.1=py311h320fe9a_0
- parquet-cpp=1.5.1=2
- partd=1.4.0=pyhd8ed1ab_0
- pbr=5.11.1=pyhd8ed1ab_0
- pcre2=10.40=hc3806b6_0
- pillow=9.5.0=py311h573f0d3_0
- pip=23.1.2=pyhd8ed1ab_0
- pixman=0.40.0=h36c2ea0_0
- pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
- platformdirs=3.1.1=pyhd8ed1ab_0
- pooch=1.7.0=pyha770c72_3
- poppler=23.04.0=hf052cbe_1
- poppler-data=0.4.12=hd8ed1ab_0
- postgresql=15.2=h3248436_0
- proj=9.2.0=h8ffa02c_0
- psutil=5.9.5=py311h2582759_0
- pthread-stubs=0.4=h36c2ea0_1001
- pyarrow=12.0.0=py311hdf9aeb4_1_cpu
- pycparser=2.21=pyhd8ed1ab_0
- pydantic=1.10.7=py311h2582759_0
- pygit2=1.12.0=py311h2582759_0
- pygments=2.15.1=pyhd8ed1ab_0
- pyiceberg=0.3.0=pyhd8ed1ab_0
- pykdtree=1.3.7.post0=py311hcb2cf0a_0
- pyopenssl=23.1.1=pyhd8ed1ab_0
- pyorbital=1.7.3=pyhd8ed1ab_0
- pyparsing=3.0.9=pyhd8ed1ab_0
- pyproj=3.5.0=py311h1850bce_1
- pyresample=1.26.1=py311h2872171_0
- pyrsistent=0.19.3=py311h2582759_0
- pysocks=1.7.1=pyha2e5f31_6
- pyspectral=0.12.3=pyhd8ed1ab_0
- python=3.11.3=h2755cc3_0_cpython
- python-dateutil=2.8.2=pyhd8ed1ab_0
- python-geotiepoints=1.6.0=py311hcb2cf0a_0
- python-tzdata=2023.3=pyhd8ed1ab_0
- python_abi=3.11=3_cp311
- pytz=2023.3=pyhd8ed1ab_0
- pyyaml=6.0=py311hd4cff14_5
- rasterio=1.3.6=py311h5998471_1
- re2=2023.02.02=hcb278e6_0
- readline=8.2=h8228510_1
- regex=2023.3.23=py311h2582759_0
- requests=2.29.0=pyhd8ed1ab_0
- rich=12.6.0=pyhd8ed1ab_0
- s2n=1.3.42=h3358134_0
- s3fs=0.4.2=py_0
- s3transfer=0.6.0=pyhd8ed1ab_0
- sarif-om=1.0.4=pyhd8ed1ab_0
- satpy=0.42.1=pyhd8ed1ab_0
- scipy=1.10.1=py311h8e6699e_1
- setuptools=67.7.2=pyhd8ed1ab_0
- shapely=2.0.1=py311h54d622a_1
- six=1.16.0=pyh6c4a22f_0
- snappy=1.1.10=h9fff704_0
- snuggs=1.4.7=py_0
- sortedcontainers=2.4.0=pyhd8ed1ab_0
- sqlite=3.40.0=h4ff8645_1
- sympy=1.11.1=pypyh9d50eac_103
- tblib=1.7.0=pyhd8ed1ab_0
- thrift=0.18.1=py311hcafe171_0
- tiledb=2.13.2=hd532e3d_0
- tk=8.6.12=h27826a3_0
- toolz=0.12.0=pyhd8ed1ab_0
- tornado=6.3=py311h2582759_0
- tqdm=4.65.0=pyhd8ed1ab_1
- trollimage=1.20.1=pyhd8ed1ab_0
- trollsift=0.5.0=pyhd8ed1ab_0
- typing-extensions=4.4.0=hd8ed1ab_0
- typing_extensions=4.4.0=pyha770c72_0
- tzcode=2023c=h0b41bf4_0
- tzdata=2023c=h71feb2d_0
- ucx=1.14.0=h3484d09_2
- urllib3=1.26.15=pyhd8ed1ab_0
- wheel=0.40.0=pyhd8ed1ab_0
- xarray=2023.4.2=pyhd8ed1ab_0
- xerces-c=3.2.4=h8d71039_2
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.0.10=h7f98852_0
- xorg-libsm=1.2.3=hd9c2040_1000
- xorg-libx11=1.8.4=h0b41bf4_0
- xorg-libxau=1.0.9=h7f98852_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.4=h0b41bf4_2
- xorg-libxrender=0.9.10=h7f98852_1003
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xproto=7.0.31=h7f98852_1007
- xyzservices=2023.2.0=pyhd8ed1ab_0
- xz=5.2.6=h166bdaf_0
- yaml=0.2.5=h7f98852_2
- zarr=2.14.2=pyhd8ed1ab_0
- zict=3.0.0=pyhd8ed1ab_0
- zipp=3.15.0=pyhd8ed1ab_0
- zlib=1.2.13=h166bdaf_4
- zstandard=0.18.0=py311hd4cff14_1
- zstd=1.5.2=h3eb15da_6
```

**Comment by Fokko** [comment] 2023-05-10 16:27
@marty-sullivan Thanks for posting the `pip freeze` and the conda yml. I recall someone else having the same issue, and that was caused by an incompatible version of boto3. S3FS relies on [`aiobotocore`](https://s3fs.readthedocs.io/en/latest/#async) (which I'm surprised to not see in the list here. `aiobotocore` has a very strict dependency on the boto3 version, and will weird errors if that doesn't match.

Could you share the versions similar as below:

```python
Python 3.9.16 (main, Dec  7 2022, 10:06:04) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'boto3' is not defined
>>> import boto3
>>> boto3.__version__
'1.24.59'
>>> import aiobotocore
>>> aiobotocore.__version__
'2.4.2'
>>> import s3fs
>>> s3fs.__version__
'2023.1.0'
```

This way I can check if the version aligns. Thank you!

**Comment by marty-sullivan** [comment] 2023-05-10 16:45
I will note, `aiobotocore` was indeed not installed, so I suppose that needs to be added as a required dependency?

Either way, installing `aiobotocore` neither solved nor changed the problem so I don't think it was related.

Here are the specific versions you requested:

```python
>>> import s3fs
>>> s3fs.__version__
'0.4.2'
>>> import aiobotocore
>>> aiobotocore.__version__
'2.5.0'
>>> import boto3
>>> boto3.__version__
'1.26.76'
```

**Comment by marty-sullivan** [comment] 2023-05-10 16:48
Since I noticed a mismatch in our versions of s3fs, I tried updating that. Updating to `s3fs.2023.5.0` did solve the problem.

I suppose this comes down to the dependency versions not being specified in conda-forge.

**Comment by Fokko** [comment] 2023-05-10 16:57
@marty-sullivan Thanks for the quick response. Appreciate it.

Thanks! It looks like that `s3fs` was not updated, version 0.4.2 (that probably comes with the base image), was from March 2020, probably relying on an old version of boto3.

**Comment by Fokko** [comment] 2023-05-10 19:39
@marty-sullivan I think we've found the underlying issue. I'll close this one, please do not hesitate to re-open it or create a new one :)

**Closed by Fokko** 2023-05-10 19:39 UTC
