### ISSUE TITLE
Rest Catalog - Bug in list namespaces. Namespaces not underneath the parent namespace are returned

### ISSUE THREAD

**Issue by jurossiar** [apache/iceberg#10443] opened 2024-06-04 17:57 UTC
### Apache Iceberg version

1.5.0

### Query engine

None

### Please describe the bug 🐞

We have the rest catalog configured with a Postgres DB.
In some cases, where namespaces have similar names, when the parent namespace is sent are returned namespaces that are not underneath the parent namespace.

Steps to reproduce it:
1) Namespaces:
   - example
   - example.auto_rag
   - example_auto_rag
   - processed
   - processed.datapile
   - processed.datapile.academic
   - processed.datapile_en
   - processed.datapile_en.common
   

E.g. 1) `v1/namespaces?parent=processed%1Fdatapile`
response:
```
{
    "namespaces": [
        [
            "processed",
            "datapile",
            "academic"
        ],
        [
            "processed",
            "datapile_en",
            "common"
        ]
    ]
}
```
The second one returned is not a child of the parent one.

E.g.. 2) `v1/namespaces?parent=example_auto_rag`
response:
```
{
    "namespaces": [
        [
            "example",
            "auto_rag"
        ]
    ]
}
```
The returned namespace is not a child of the parent one.

**Comment by ajantha-bhat** [comment] 2024-06-05 11:10
Iceberg doesn't maintain an implementation of the REST catalog server. Only spec is defined at the Iceberg repo.
Spec clearly says, listNamespaces should list the namespaces at certain level. 
https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L192-L212

which vendor implementation of REST catalog server are you using? Maybe raise a bug in their repo?

**Comment by jurossiar** [comment] 2024-06-05 12:20
We are using tabulario: https://hub.docker.com/r/tabulario/iceberg-rest/tags
I've just took a look in the [repo](https://github.com/tabular-io/iceberg-rest-image) and in a first glance seems that the implementation on how to process the request is not there.

I think the issue could be related to this code: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java#L228

Please, let me know if you still think is not something to report here. Thanks!

**Comment by nastra** [comment] 2024-06-06 09:44
Is it possible that this is the same issue that was described in https://github.com/apache/iceberg/issues/10213 (aka it's an issue with `JdbcCatalog`)? The `RESTCatalog` only acts as a proxy when you're using an underlying catalog that is JDBC

**Comment by jurossiar** [comment] 2024-06-06 12:16
@nastra Yes, it's true! I forgot I did a better analysis last time and created that issue. It's the same issue and now we have more cases. I found more cases and reported it again. 
I think that LIKE must be replaced by equal (=).

**Comment by jurossiar** [comment] 2024-06-06 12:17
Feel free to close some of them.

**Comment by nastra** [comment] 2024-06-06 13:24
I'll close this one since it's a duplicate of https://github.com/apache/iceberg/issues/10213

**Closed by nastra** 2024-06-06 13:24 UTC
Labels: bug
