### ISSUE TITLE
i cant table create dayTransform() and monthTransform() togetger for single field in schema

### ISSUE THREAD

**Issue by dvnageshpatil** [apache/iceberg#11788] opened 2024-12-14 10:44 UTC
getting redundant partitons error

**Comment by ebyhr** [comment] 2024-12-14 11:39
I think that's the expected behavior:

https://github.com/apache/iceberg/blob/540d6a6251e31b232fe6ed2413680621454d107a/api/src/test/java/org/apache/iceberg/TestPartitionSpecValidation.java#L63-L65

**Comment by dvnageshpatil** [comment] 2024-12-14 11:56
If I have timestamp field .same field we can use to make transformation for day and month and year transformations instead of having duplicate field in schema

**Comment by Fokko** [comment] 2024-12-16 15:27
@dvnageshpatil If you have a timestamp value:

```
ts = '2024-10-22T19:25:00'
```

Then the transforms will produce:

```
day(ts) = '2024-10-22'
month(ts) = '2024-10'
```

In this case, the `month` information is useless since it is also encoded in the `day` information. Therefore just adding a `day` partition transform will do it 👍 I hope this helps! I'll close this issue for now, feel free to re-open it if there are any further questions.

**Closed by Fokko** 2024-12-16 15:27 UTC
