### ISSUE TITLE
Fails to insert into iceberg table after dropping a partition column that was used by older partition specs

### ISSUE THREAD

**Issue by lurnagao-dahua** [apache/iceberg#7415] opened 2023-04-23 08:03 UTC
### Apache Iceberg version

1.2.0

### Please describe the bug 🐞

`format-version=2`

1.schema and spec:
`Types.NestedField.required(1, "id", Types.IntegerType.get());`
`Types.NestedField.required(2, "name", Types.StringType.get());`
`Types.NestedField.required(3, "dt", Types.StringType.get());`
`PartitionSpec.builderFor(schema).identity("dt").build();`

2.drop spec field
`table.updateSpec().removeField("dt").commit`

3.drop schema field
`table.updateSchema().deleteColumn("dt").commit`

4.hivesql insert will throw npe:
`Exception in thread "main" java.lang.NullPointerException: Type cannot be null
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at org.apache.iceberg.types.Types$NestedField.<init>(Types.java:449)
	at org.apache.iceberg.types.Types$NestedField.optional(Types.java:418)
	at org.apache.iceberg.PartitionSpec.partitionType(PartitionSpec.java:141)
	at org.apache.iceberg.util.PartitionSet.lambda$new$0(PartitionSet.java:45)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at org.apache.iceberg.util.PartitionSet.<init>(PartitionSet.java:45)
	at org.apache.iceberg.util.PartitionSet.create(PartitionSet.java:37)
	at org.apache.iceberg.ManifestFilterManager.<init>(ManifestFilterManager.java:91)
	at org.apache.iceberg.MergingSnapshotProducer$DataFileFilterManager.<init>(MergingSnapshotProducer.java:701)
	at org.apache.iceberg.MergingSnapshotProducer$DataFileFilterManager.<init>(MergingSnapshotProducer.java:699)
	at org.apache.iceberg.MergingSnapshotProducer.<init>(MergingSnapshotProducer.java:117)
	at org.apache.iceberg.MergeAppend.<init>(MergeAppend.java:32)`

**Comment by Fokko** [comment] 2023-04-23 18:47
@lurnagao thanks for reporting. Looks like this is a duplicate of https://github.com/apache/iceberg/issues/7386

**Comment by Fokko** [comment] 2023-04-23 18:49
As a workaround, you could upgrade the table format to version 2.

**Comment by lurnagao** [comment] 2023-04-24 00:46
> As a workaround, you could upgrade the table format to version 2.

Hi, when I use the v2, the same problem happens

**Comment by yikuanlee** [comment] 2023-09-21 11:46
was able to re-produce from hive-iceberg-handler for format-version=2. NPE for both read/write 
Any idea of the root cause ? not sure why it did not read current partition spec.
```
Error while getting Storage Handler splits for: org.apache.iceberg.mr.hive.HiveIcebergInputFormat
java.lang.NullPointerException: Type cannot be null
        at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) 
        at org.apache.iceberg.types.Types$NestedField.<init>(Types.java:446)
        at org.apache.iceberg.types.Types$NestedField.optional(Types.java:415) 
        at org.apache.iceberg.PartitionSpec.partitionType(PartitionSpec.java:132)
        at org.apache.iceberg.DeleteFileIndex.lambda$new$0(DeleteFileIndex.java:84) 
        at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292)
        at org.apache.iceberg.DeleteFileIndex.<init>(DeleteFileIndex.java:84
        at org.apache.iceberg.DeleteFileIndex$Builder.build(DeleteFileIndex.java:525)
        at org.apache.iceberg.ManifestGroup.plan(ManifestGroup.java:182)
        at org.apache.iceberg.ManifestGroup.planFiles(ManifestGroup.java:169)
        at org.apache.iceberg.DataTableScan.doPlanFiles(DataTableScan.java:103)
        at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:152)
        at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:27)
        at org.apache.iceberg.BaseTableScan.planTasks(BaseTableScan.java:178)
        at org.apache.iceberg.DataTableScan.planTasks(DataTableScan.java:27)
        at org.apache.iceberg.mr.mapreduce.IcebergInputFormat.getSplits(IcebergInputFormat.java:174)
        at org.apache.iceberg.mr.mapred.MapredIcebergInputFormat.getSplits(MapredIcebergInputFormat.java:69)
        at org.apache.iceberg.mr.hive.HiveIcebergInputFormat.getSplits(HiveIcebergInputFormat.java:144)
 ```

**Comment by Fokko** [comment] 2023-09-21 12:16
Did you delete one of the fields that is part of the partition spec?

Which version are you using? This has been fixed in 1.3, are you able to upgrade?

**Comment by yikuanlee** [comment] 2023-09-21 12:42
yes, drop partition field of the column then drop the column then insert/write get npe.
we are using hive-iceberg-handler-4.0.0-alpha-2.jar
Per hive4-alpha2 release note. it said iceberg version 0.14.1

**Comment by Fokko** [comment] 2023-09-22 13:09
Thank you. 0.14.1 has this bug indeed. Let me know if it works.

**Closed** 2024-06-15 02:20 UTC
